### ISSUE TITLE
"rhel-8" runner runs RHEL 8.3 but uses 8.4 content

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#1599]
Having this kind of configuration:
```yaml
  parallel:
    matrix:
      - RUNNER:
          - aws/fedora-33-x86_64
          - aws/fedora-33-aarch64
          # Enable f34 once we have rpmrepo snapshots for it
          - aws/rhel-8-x86_64
          - aws/rhel-8-aarch64
          - aws/centos-stream-8-x86_64
          - aws/centos-stream-8-aarch64
      - RUNNER:
          - aws/rhel-8.5-x86_64
```
I'd expect rhel-8 runners to use the latest released version of RHEL which is 8.4. Because that is what we build RPMs for in Schutzbot. But it turns out the runner uses RHEL8.3 image, official repos from CDN (8.4?) and 8.4 osbuild-composer and osbuild RPMs.

The confusing part is that we have 8.4 repository overrides defined in `test/data` but it is not used because the system is not 8.4: https://github.com/osbuild/osbuild-composer/blob/4729990ac002ced7f44cab59269e07f9e835d1e4/tools/provision.sh#L59
