### ISSUE TITLE
[RFE] warn when creating RHEL for Edge Installer image reusing existing blueprint

### ISSUE THREAD

**Issue by miabbott** [osbuild/osbuild-composer#3106]
When a user follows the workflow to create a RHEL for Edge Installer image, it is easy to end up with a non-working ISO by reusing the same blueprint. 

Given the following blueprint:

```toml
name = "first-time-user"
description = ""
version = "0.0.0"
packages = []
modules = []
groups = []
distro = ""

[customizations]

[[customizations.user]]
name = "core"
password = "<hashed password>"
key = "ssh-rsa AAA....
groups = ["wheel"]
```

If I create an ostree commit with that blueprint, then create the installer ISO with the same blueprint, the installation will fail with the following message from Anaconda: `dasbus.error.DBusError: set_user_ssh_key: user core does not exist`

This is incredibly frustrating as an end user because the blueprint contains customizations that define a user and so my expectation is that the user *does* exist.

I feel like there is some room for improvement here because the limitation about reusing the same blueprint is not obvious.

Perhaps this is something that could be done on the web UI and harder to do from the CLI, but it seems worth exploring.
