### ISSUE TITLE
Blueprint schema updates cause updated blueprint pushes to end up with missing fields

### ISSUE THREAD

**Issue by 7flying** [osbuild/osbuild-composer#3167]
**Describe the bug**

If you change the schema of a blueprint, for instance:
```go
Data64          string `json:"ignition_data,omitempty" toml:"ignition_data,omitempty"`
```
to
```go
Data64          string `json:"data,omitempty" toml:"data,omitempty"`
```

then update an associated blueprint that has been already pushed (aka bump the version and replace the old field with the new field and `push` it), when  you `show` the blueprint the new updated field will not show up. No errors/warnings on the logs.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): Red Hat Enterprise Linux release 9.1 (Plow)
 * osbuild-composer version (`rpm -qi osbuild-composer)`: upstream version, latest commit `5457b9fba2ef634e5be798c8503842d749ec29df`

**To Reproduce**

Use the following PR branch: https://github.com/osbuild/osbuild-composer/pull/3161,
* push the following blueprint
 ```toml
name = "embedded-data"
description = ""
version = "0.0.1"

[customizations]
installation_device = "/dev/vda"

[customizations.ignition.embedded]
data = "eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHA6Ly8xOTIuMTY4\nLjEyMi4xOjgwMDAvc2FtcGxlLmlnbiJ9XX0sInRpbWVvdXRzIjp7Imh0dHBUb3RhbCI6MzB9LCJ2\nZXJzaW9uIjoiMy4zLjAifSwicGFzc3dkIjp7InVzZXJzIjpbeyJncm91cHMiOlsid2hlZWwiXSwi\nbmFtZSI6ImNvcmUiLCJwYXNzd29yZEhhc2giOiIkNiRqZnVObk85dDFCdjdOLjdrJEhxUnhxMmJs\ndFIzek15QUhqc1N6YmU3dUJIWEVyTzFZdnFwaTZsamNJMDZkUUJrZldYWFpDdUUubUpja2xQVHdh\nQTlyL3hwSmlFZFdEcXR4bGU3aDgxIiwic3NoQXV0aG9yaXplZEtleXMiOlsic3NoLWVkMjU1MTkg\nQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUJXT0dlNTFyNDA0SlNYRW5hbktaampCOHJVb2hnMWRB\nYXpydDFKd3lNVXogY2FyZG5vOjAwMDAgQTAxMDMxMjUiXX1dfSwic3RvcmFnZSI6eyJmaWxlcyI6\nW3sicGF0aCI6Ii9ldGMvTmV0d29ya01hbmFnZXIvc3lzdGVtLWNvbm5lY3Rpb25zL2VucDFzMC5u\nbWNvbm5lY3Rpb24iLCJjb250ZW50cyI6eyJjb21wcmVzc2lvbiI6Imd6aXAiLCJzb3VyY2UiOiJk\nYXRhOjtiYXNlNjQsSDRzSUFBQUFBQUFDLzB5S1VjckNNQkFHMy9jc2YvT2JVS1FpZTVMU2h5WDVT\nZ1BOTmlTcjBOdUxnaUR6Tk1QTThWQkZ0SHpvUWpreHRQcCtJVHNyR0xhaEtZeXlHdG9xRVlOS3dm\nZVpjMzJPQzBsS0RiMTc5cmZnL0hWeVBnUTNodjh3L3YwV1QwazdUKzdEL1MxRGg3UzRNUlU1aDFY\neXpxdnNIVlJnMjVHNGlENWtwMWNBQUFELy82Q3ZxMmloQUFBQSJ9LCJtb2RlIjozODR9LHsicGF0\naCI6Ii91c3IvbG9jYWwvYmluL3N0YXJ0dXAuc2giLCJjb250ZW50cyI6eyJzb3VyY2UiOiJkYXRh\nOjtiYXNlNjQsSXlFdlltbHVMMkpoYzJnS1pXTm9ieUFpU0dWc2JHOHNJRmR2Y214a0lTSUsifSwi\nbW9kZSI6NDkzfV19LCJzeXN0ZW1kIjp7InVuaXRzIjpbeyJjb250ZW50cyI6IltVbml0XVxuRGVz\nY3JpcHRpb249QSBoZWxsbyB3b3JsZFxuW0luc3RhbGxdXG5XYW50ZWRCeT1tdWx0aS11c2VyLnRh\ncmdldCIsImVuYWJsZWQiOnRydWUsIm5hbWUiOiJoZWxsby5zZXJ2aWNlIn0seyJkcm9waW5zIjpb\neyJjb250ZW50cyI6IltTZXJ2aWNlXVxuRW52aXJvbm1lbnQ9TE9HX0xFVkVMPXRyYWNlXG4iLCJu\nYW1lIjoibG9nX3RyYWNlLmNvbmYifV0sIm5hbWUiOiJmZG8tY2xpZW50LWxpbnV4YXBwLnNlcnZp\nY2UifV19fQo="
 ```
 
*  change the `data` field to whatever you like in `internal/blueprint/customizations.go`
* re-compile
* update the previous blueprint bumping the version and updating the changed field name
* `push` this new updated blueprint
* `show` and you will get a blueprint with the updated section missing:
```toml
name = "new-blueprint"
description = ""
version = "0.0.2"
packages = []
modules = []
groups = []
distro = ""

[customizations]
installation_device = "/dev/vda"
```

**Expected behavior**
I would expect that the new pushed blueprint would get the updated schema.

**Additional context**
