### ISSUE TITLE
iot-simplified-installer changes admin password on fedora 38

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/osbuild-composer#3526]
**Describe the bug**
after boot iot-simplified-installer, when try to login with user admin, and then input the password defined in blueprint, os prompts incorrect password. But can login user admin with the ssh key defined in blueprint

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): fedora-38
 * osbuild-composer version (`rpm -qi osbuild-composer)`

**To Reproduce**
1. build iot-container, define user/password/sshkey in the blueprint.
```toml
name = "container"
description = "A base rhel-edge container image"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "python3"
version = "*"

[[customizations.user]]
name = "admin"
description = "Administrator account"
password = "**********PASSWORD**********************"
key = "${SSH_KEY_PUB}"
home = "/home/admin/"
groups = ["wheel"]
```

2. build iot-simplified-installer
```toml
name = "simplified"
description = "A rhel-edge simplified-installer image"
version = "0.0.1"
modules = []
groups = []

[customizations]
installation_device = "/dev/vda"
```

3. boot and then login with admin, the password I input is incorrect.
```
[root@yih-f38 rhel-edge]# ssh admin@192.168.100.51
The authenticity of host '192.168.100.51 (192.168.100.51)' can't be established.
ED25519 key fingerprint is SHA256:qwJ34cWARtAPqRO8Ehu628l4Chiq8NuKLh++Dtt1PXs.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.100.51' (ED25519) to the list of known hosts.
admin@192.168.100.51's password: 
Permission denied, please try again.
admin@192.168.100.51's password: 
Permission denied, please try again.
```

Then I used the ssh key to login.
```
[root@yih-f38 rhel-edge]# ssh -i key/ostree_key admin@192.168.100.51
Script '01_update_platforms_check.sh' FAILURE (exit code '1'). Continuing...
Boot Status is GREEN - Health Check SUCCESS
Last failed login: Tue Jun 27 14:06:41 UTC 2023 from 192.168.100.1 on ssh:notty
There were 2 failed login attempts since the last successful login.
```

Then when I try to run sudo command, the password is still incorrect
```
[admin@localhost boot]$ sudo cryptsetup luksDump /dev/vda4

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

[sudo] password for admin: 
Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
```

**Expected behavior**
should be able to login with password defined

**Additional context**
