### ISSUE TITLE
Unable to build images with Microsoft SQL packages - cannot pass environment variables or respond to prompts

### ISSUE THREAD

**Issue by richm** [osbuild/osbuild-composer#3940]
**Describe the bug**
Some of the Microsoft SQL packages require the user to accept the EULA before or during installation, either by setting an environment variable (`ACCEPT_EULA=y`), or by the package interactively prompting the user on the terminal.  For example:

```
https://packages.microsoft.com/rhel/9/prod/Packages/m/mssql-tools-17.10.1.1-1.x86_64.rpm

rpm -qp --scripts mssql-tools-17.10.1.1-1.x86_64.rpm

preinstall scriptlet (using /bin/sh):
check_eula_acceptance()
{
	if [ "$ACCEPT_EULA" != "y" ] && [ "$ACCEPT_EULA" != "Y" ]; then
    	exec 2>/dev/tty 1>&2 </dev/tty
…
```

The problem is that the image builder does not have a way to pass such environment variables through to the package manager, or deal with such interactive prompts.

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`): any
 * osbuild-composer version (`rpm -qi osbuild-composer)`: any

**To Reproduce**
 * *for example starting osbuild-composer.service or running composer-cli command, don't forget to include all configuration files you created*

Configure the Microsoft SQL server repositories (however repositories are configured):
```
[mssql_server_2022]
name=Microsoft SQL Server 2022
baseurl=https://packages.microsoft.com/rhel/9/mssql-server-2022
enabled=1
gpgcheck=1

[mssql_client]
name=Microsoft SQL Client
baseurl=https://packages.microsoft.com/rhel/9/prod
enabled=1
gpgcheck=1
```
Configure the list of packages to be installed:
```toml
[[packages]]
name = "mssql-server"
version = "*"
[[packages]]
name = "mssql-server-fts"
version = "*"
[[packages]]
name = "mssql-server-ha"
version = "*"
[[packages]]
name = "mssql-server-selinux"
version = "*"
[[packages]]
name = "mssql-tools"
version = "*"
[[packages]]
name = "powershell"
version = "*"
[[packages]]
name = "unixODBC-devel"
version = "*"
```

The image build will fail

**Expected behavior**
Image building will succeed

**Additional context**

**Comment by bcl** [comment]
@achilleas-k and @richm and I discussed this on slack a bit today.

One idea is to add the ability to include environmental variables with the packages. eg.

```toml
[[packages]]
name = "mssql-tools"
version = "*"
environment = ["ACCEPT_EULA=y"]
```

It's not a great idea, it requires plumbing this down through all the layers to the rpm stage in osbuild. But I don't really see any better way. Limiting it to the specific package would prevent the environment accidentally leaking into other packages and possibly causing problems.

Another alternative is that `mssql` adds the ability to check for a known file to indicate acceptance of the EULA, and then you can use `customizations.files` to create it. Currently that is limited to `/etc` so we may need to talk about allowing files elsewhere.
