### ISSUE TITLE
Empty name blueprint should not be allowed to create

### ISSUE THREAD

**Issue by henrywang** [osbuild/osbuild-composer#522]
Blueprint with empty name can be created.
```toml
name = ""
description = ""
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "openssh-server"
version = "*"
```
The `state.json` confirmed empty name blueprint have been pushed into store.
```json
{"blueprints":{"":{"name":"","description":"","version":"0.0.1","packages":[{"name":"openssh-server","version":"*"}],"modules":[],"groups":[]}},"workspace":{},"composes":{},"sources":{},"changes":{"":{"c3743814b30e0bb2a5c607d6f85f22e1e126c879":{"commit":"c3743814b30e0bb2a5c607d6f85f22e1e126c879","message":"Recipe , version 0.0.1 saved.","revision":null,"timestamp":"2020-04-21T22:57:37Z"}}},"commits":{"":["c3743814b30e0bb2a5c607d6f85f22e1e126c879"]}}
```

The API "blueprints/new" or "store.push" should have a name validation. Empty name should not be allowed, and the API should response an error message.
