### ISSUE TITLE
RFC/POC: end-to-end test cases as ansible plays

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#655]
I want to propose creating our end-to-end test scenarios as ansible plays that could be ran with schutzbot. I think this will mimic how a user would use osbuild-composer which is what we want. What I'm not sure about is if this is the way we want to implement it. My first play looks like this:
```
- name: "first test"
  hosts: localhost
  tasks:
    - name: "Make sure osbuild-composer.socket is installed"
      dnf:
        name:
          - osbuild-composer
          - composer-cli
        state: present
    - name: "Make sure osbuild-composer is started"
      service:
        name: osbuild-composer.socket
        state: started
    - name: "Create a basic blueprint"
      copy:
        dest: "base.toml"
        content: |
          name = "base"
          description = "A base system with bash"
          version = "0.0.1"
          modules = []
          groups = []
 
          [[packages]]
          name = "bash"
          version = "*"
 
          [customizations]
          hostname = "test-image"
 
          [[customizations.user]]
          name = "test_user"
          password = "$6$d4C/rAdVMPPoCCoq$a20HKMJV406hbwHmazr6xWzvYYbUyDCrJDl.vFysg0ZdHW282JfckqtEsPLdQnzWNy2b6zj26cQVJPq/gd8HT/"
          groups = ["wheel"]
    - name: "Upload the blueprint"
      command: "composer-cli blueprints push base.toml"
    - name: "Start an qcow2 compose"
      command: "composer-cli compose start base qcow2"
      register: result
    - set_fact:
        UUID: "{{ result.stdout | regex_search('\\S{36}') }}"
    - name: "Wait for compose to finish"
      command: "composer-cli compose status"
      register: result
      delay: 15
      retries: 60
      until: result.stdout.find("FINISHED") != -1
    - name: "Download finished image"
      command: "composer-cli compose image {{ UUID }}"
    - name: "start libvirtd"
      service:
        name: libvirtd.service
        state: started
    - name: "create vm"
      command: "virt-install -n foobar --memory 2048 --nographics --import --disk {{ UUID }}-disk.qcow2 --noautoconsole --os-variant fedora32"
    - name: "check VM"
      virt:
        name: foobar
```
I suppose that this would share a common setup phase and possibly use some clean up phase. I'm not sure about the end if this check is enough, maybe a successful ssh connection into the booted VM would be nice to have. @major already tried something like this over at ansible-osbuild https://github.com/osbuild/ansible-osbuild/blob/master/schutzbot/composer-smoke-test.yml but we agreed it should be in osbuild-composer repo. Maybe have another task in https://github.com/osbuild/osbuild-composer/blob/master/schutzbot/test.yml and include these kind of scenarios there similar to how the other tests are ran now? Any thoughts about this @atodorov @teg ?
