### ISSUE TITLE
cloud-init installed, but services not started

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#698]
While working on ansible-osbuild's smoke tests in osbuild/ansible-osbuild#72, I found a problem with the `qcow2` and `openstack` image outputs. They have `cloud-init` installed, but none of the services/targets are enabled.

I used the following blueprint:

```toml
name = "bash"
description = "A base system with bash"
version = "0.0.1"

[[packages]]
name = "bash"
```

Then I started the build with `composer-cli --json compose start bash qcow2`. Fedora 31/32's cloud-init package does not enable cloud-init's services/targets by default and both images failed to prepare the user I asked for in my cloud-init config. RHEL 8 was working fine, but its cloud-init package has [some hacks](https://src.osci.redhat.com/rpms/cloud-init/blob/rhel-8.2.1/f/cloud-init.spec#_134) to ensure services are started after installation.

When I used the following blueprint, all distros worked:

```toml
name = "bash"
description = "A base system with bash"
version = "0.0.1"

[[packages]]
name = "bash"

[customizations.services]
enabled = ["sshd", "cloud-init", "cloud-init-local", "cloud-config", "cloud-final"]
```

As a user, I would expect cloud-init to always be running on bootup whether I asked for it to be started explicitly or not.
